### ISSUE TITLE
Choix technos pour la suite

### ISSUE THREAD

**Issue by chrisnoisel** [LPFP/donjon#1]
Pas vraiment une "issue" mais puisqu'il a été proposé d'en parler publiquement ici, je me lance.

J'ai relu vite fait les derniers commits, à priori c'est ok pour moi dans la mesure où l'on se rapproche d'un site modulaire (e.g. menu déclaré en 1 seul endroit etc.).
Pour la suite et avant d'aller trop loin je propose de passer la partie vue sur un système de templates (perso en PHP j'utilisais Smarty), ainsi on sépare le php et ça permet aux contributeurs qui ne font que de intégration html de ne pas se mélanger. Et qui sait, peut-être que dans le futur on se mettra à produire du json en plus de la partie web ? cc @ExtraBlind @pepinpin

**Comment by extrablind** [comment]
Pourquoi pas un moteur de template même si l'utilité me semble limité, ca permettra aux gens de ne pas se mélanger les pinceaux. Par contre je penche plutôt pour Twig qui est plus complet et avec une syntaxe plus agréable.

**Comment by chrisnoisel** [comment]
Disons que le système de templates est structurant, suffit de suivre le modèle de page et tout le monde adopte la même structure mvc.
J'ai regardé vite fait Twig et ça m'a l'air ok, je te fais confiance pour la comparaison avec Smarty que je n'ai pas vraiment utilisé depuis bien bien longtemps.

Euhm sinon je ne sais pas ce que vous avez prévu d'intégrer dynamiquement dans le site, pour l'instant ça me semble être un gros bout de HTML sans base de données derrière.
J'ai lu dans les mails qu'il était question d'internaliser certains outils Google (j'imagine faire sauter des iframe), vous avez une priorité sur les travaux à faire ?

**Comment by extrablind** [comment]
Etant donné qu'on s'est orienté sur cakephp lors de la dernière réunion, il faut utiliser du PHP pure pour l'instant mais twig est dispo sous forme de plugin cf : https://github.com/WyriHaximus/TwigView 
On pourra donc l'intégrer

**Comment by chrisnoisel** [comment]
Si je ne me trompe pas, cakePHP impose le MVC, donc c'est déjà pas mal.

**Comment by extrablind** [comment]
Oui, je pense qu'on peut fermer ce ticket.
